config/routes.rb
Northcantonchurch::Application.routes.draw do

  root :to => 'main#content_page'

  mount Ckeditor::Engine => '/ckeditor'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }, :path_names => {:sign_in => 'login', :sign_out => 'logout'}
  devise_scope :user do
    get "/logout" => "devise/sessions#destroy"
  end

  resources :files
  resources :file_browsers

  resources :user_sessions
  
  resources :pages, :menu_items

  namespace :admin do
    resources :pages
    resources :menu_items
    post "menu_items/sort" => 'menu_items#sort'
    resources :images
    match '/page-versions/show/:id' => 'page_versions#show', :as => "page_versions_show"
    match '/page-versions/restore/:id' => 'page_versions#restore', :as => "page_versions_restore"
    resources :users
    post 'users/toggle-admin' => 'users#toggle_admin'
  end

  match '/admin' => 'admin#index', :as => 'admin'

  match ':controller/:action/:id'
  match ':controller/:action/:id.:format'

  #All content pages
  match ':path' => 'main#content_page'
end

app/views/admin/pages/_form.html.erb
<div class='row-fluid'>
  <div class='span9'>
<%= form_for([:admin, @page], :html => {:class =>'form-horizontal'}) do |f| %>
  <%= render 'shared/error_messages', :target => @page %>

  <% title_error = 'error' if @page.errors.include?(:title) %>
  <%= content_tag :div, :class => "control-group #{title_error}" do %>
    <%= label_tag :title, "Title", :class => 'control-label' %>
    <%= content_tag :div, :class => 'controls' do %>
      <%= f.text_field :title, :class => 'input-xlarge' %>
    <% end %>
  <% end %>

  <%= content_tag :div, :class => 'control-group' do %>
    <%= f.label :keywords, :class => 'control-label'  %>
    <%= content_tag :div, :class => 'controls' do %>
      <%= f.text_field :keywords, :class => 'input-xlarge' %>
    <% end %>
  <% end %>

  <%= content_tag :div, :class => 'control-group' do %>
    <%= f.label :description, :class => 'control-label' %>
    <%= content_tag :div, :class => 'controls' do %>
      <%= f.text_field :description, :class => 'input-xlarge' %>
    <% end %>
  <% end %>

  <%= content_tag :div, :class => 'control-group' do %>  
    <%= f.label :url_tag, :class => 'control-label' %>
    <%= content_tag :div, :class => 'controls' do %>
      <%= content_tag :div, :class => 'input-prepend' do %>
        <%= content_tag(:span, "#{request.protocol + request.host_with_port}/", :class => 'add-on') %><%= f.text_field :url_tag, :class => 'span3', :size => 16 %>
      <% end %>
    <% end %>
  <% end %>

  <% content_error = 'error' if @page.errors.include?(:content) %>
  <%= content_tag :div, :class => "control-group #{content_error}" do %>
    <%= label_tag :content, "Content", :class => 'control-label' %>
    <%= content_tag :div, :class => 'controls' do %>
      <%#= f.text_area(:content, :cols => 40, :rows => 15 )%>
      <%= cktext_area_tag(:content, @page.content, :input_html => {:cols => 10, :rows => 20, :name => 'page[content]'}, :toolbar => 'Full') %>
      <%= content_tag :span, :class => 'help-inline error' do %>
        <%= @page.errors[:content].join(', ')	 %>
     <% end if @page.errors.include?(:content) %>
    <% end %>
  <% end %>

  <%= content_tag :div, :class => 'control-group' do %>
    <%= f.label :published, :class => 'control-label' %>
    <%= content_tag :div, :class => 'controls' do %>
      <%=  f.check_box :published %>
    <% end %>
  <% end %>
  <%= content_tag :div, :class => 'form-actions' do %>
    <%= f.submit submit_text, :class => "btn-primary" %>
    <%= link_to 'Cancel', admin_pages_path, :class => 'btn' %>
  <% end %>
<% end %>
  </div>
  <div class='span3 image-sidebar'>
    <div id='image-list'>
      <%= render :partial => 'admin/images/list' %>
    </div>
    <%= content_tag :table, :class => "table table-striped table-bordered" do %>
    <tr>
      <th>Upload a new Image</th>
    </tr>
    <tr>
      <td><%= render :partial => 'admin/images/form' %></td>
    </tr>
    <% end %>
  </div>
</div>

app/views/admin/pages/edit.html.erb
<div class='page-header'>  
  <h1>Page Edit</h1>
</div>
  <%= render :partial => 'form', :locals => {:submit_text => "Save Page"} %>

app/views/admin/pages/index.html.erb
<%= content_tag :div, :class => 'page-header' do %>
  <%= content_tag :h1 do %>
  Page List
  <% end %>
<% end %>

<%= content_tag :table, :class => "table table-striped table-bordered" do %>
  <%= content_tag :thead do %>
    <%= content_tag :tr do %>
      <%= content_tag :th, 'Title' %>
      <%= content_tag :th, 'URL Tag' %>
      <%= content_tag :th, 'Last Modified' %>
      <%= content_tag :th, 'Action' %>
    <% end %>
  <% end %>

  <% @pages.each do |page| %>
    <%= content_tag :tr do %>
      <%= content_tag :tbody do %>
        <%= content_tag :td, page.title %>
        <%= content_tag :td, page.url_tag %>
        <%= content_tag :td, page.updated_at.strftime("%d-%B-%Y %I:%M%p") %>
        <%= content_tag :td do %>
          <%= link_to "<i class='icon-edit icon-white'></i>&nbsp;Edit".html_safe, 
                      edit_admin_page_path(page), 
                      :class => 'btn btn-primary' %>
          <%#= link_to "<i class='icon-time icon-white'></i>&nbsp;Restore".html_safe, 
                      admin_page_path(page), 
                      :class => 'btn btn-warning' %>
          <%= link_to "<i class='icon-trash icon-white'></i>&nbsp;Delete".html_safe,
                      [:admin, page], 
                      :confirm => 'Are you sure?', 
                      :method => :delete, 
                      :id => "destroy_#{page.id}", 
                      :class => 'btn btn-danger delete-page',
                      "data-content" => 'This will irreversibly delete this page.', 
                      "data-original-title" => 'Are You Sure?' %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
<% end%>

<br />
<%= will_paginate @pages %>
<hr>
<%= link_to "<i class='icon-play-circle icon-white'></i>&nbsp;Add a Page".html_safe, 
            new_admin_page_url, 
            :class => 'btn btn-success' %>

app/views/admin/pages/new.html.erb
<div class='page-header'>
  <h1>New Page</h1>
</div>
<%= render :partial => 'form', :locals => {:submit_text => "Create Page"} %>

app/views/admin/pages/show.html.erb
<table>
  <tr>
    <th>&nbsp;</th>
    <th>Version</th>
    <th>Date</th>
    <th>Content</th>
  </tr>
  <% @page.versions.reverse.each do |version| %>
  <tr>
    <td><%= link_to "View", admin_page_versions_show_url(version) %></td>
    <td><%= version.version %></td>
    <td><%= version.updated_at %></td>
    <td><%= version.content %></td>
  </tr>
  <% end %>
</table>

<h2>Current Version</h2>
Title: <%= @page.title  %><br />
Last Update: <%= @page.updated_at %><br />
Content: <%= @page.content.html_safe %>