config/routes.rb
Northcantonchurch::Application.routes.draw do

  root :to => 'main#content_page'

  mount Ckeditor::Engine => '/ckeditor'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }, :path_names => {:sign_in => 'login', :sign_out => 'logout'}
  devise_scope :user do
    get "/logout" => "devise/sessions#destroy"
  end

  resources :files
  resources :file_browsers

  resources :user_sessions
  
  resources :pages, :menu_items

  namespace :admin do
    resources :pages
    resources :menu_items
    post "menu_items/sort" => 'menu_items#sort'
    resources :images
    match '/page-versions/show/:id' => 'page_versions#show', :as => "page_versions_show"
    match '/page-versions/restore/:id' => 'page_versions#restore', :as => "page_versions_restore"
    resources :users
    post 'users/toggle-admin' => 'users#toggle_admin'
  end

  match '/admin' => 'admin#index', :as => 'admin'

  match ':controller/:action/:id'
  match ':controller/:action/:id.:format'

  #All content pages
  match ':path' => 'main#content_page'
end

app/models/image.rb
class Image < ActiveRecord::Base
  mount_uploader :image, ImageUploader
end

app/controllers/admin/images_controller.rb
class Admin::ImagesController < AdminController
  # GET /admin/images
  # GET /admin/images.json
  def index
    @admin_images = Image.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @admin_images }
    end
  end

  # GET /admin/images/1
  # GET /admin/images/1.json
  def show
    @admin_image = Image.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @admin_image }
    end
  end

  # GET /admin/images/new
  # GET /admin/images/new.json
  def new
    @admin_image = Image.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @admin_image }
    end
  end

  # GET /admin/images/1/edit
  def edit
    @admin_image = Image.find(params[:id])
  end

  # POST /admin/images
  # POST /admin/images.json
  def create
    @admin_image = Image.new(params[:admin_image])
    respond_to do |format|
      if @admin_image.save
        format.html { redirect_to admin_images_url, notice: 'Image was successfully created.' }
        format.json do
          @images = Image.all
          render :json => { :image_list => render_to_string(:partial => 'admin/images/list.html.erb') }
        end
      else
        format.html { render action: "new" }
        format.json { render json: @admin_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admin/images/1
  # PUT /admin/images/1.json
  def update
    @admin_image = Image.find(params[:id])

    respond_to do |format|
      if @admin_image.update_attributes(params[:admin_image])
        format.html { redirect_to @admin_image, notice: 'Image was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @admin_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/images/1
  # DELETE /admin/images/1.json
  def destroy
    @admin_image = Image.find(params[:id])
    @admin_image.destroy

    respond_to do |format|
      format.html { redirect_to admin_images_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/admin/images_helper.rb
module Admin::ImagesHelper
end

app/views/admin/images/_form.html.erb
<%= form_for([:admin, @admin_image], :as => :admin_image, :html => {:multipart => true}) do |f| %>
  <%= render 'shared/error_messages', :target => @admin_image %>

  <div class="control-group">
    <%= f.file_field :image %>
    <%= f.hidden_field :image_cache %>
  </div>

  <div class="form-actions">
    <%= f.submit "Upload Image", :class => 'btn-primary', :id => 'image-upload-submit' %>
    <span id="image-upload-spinner" style='float:right; margin: 15px 95px 15px 0px;', class='--btn-primary'></span>
  </div>
<% end %>

app/views/admin/images/_list.html.erb
<%= content_tag :table, :class => "table table-striped table-bordered" do %>
  <thead>
    <%= content_tag :tr do %>
      <%= content_tag :th, 'Click a size to insert image at cursor' %>
    <% end %>
  </thead>
  <tbody>
    <tr><td>
    <% @images.each do |image| %>
    <div class='image-list-item'>
      <span class='image-item-wrap'><%= image_tag image.image.thumb.url, :class => 'image-item', :id => dom_id(image) %></span><br>
      &nbsp;<span class="insertable-image" data-url=<%= image.image.url %>>O</span>&nbsp;
			<span class="insertable-image" data-url=<%= image.image.medium %>>M</span>&nbsp;
			<span class="insertable-image" data-url=<%= image.image.large %>>L</span>
		</div>
    <% end %>
    </td></tr>
  </tbody>
<% end %>

app/views/admin/images/edit.html.erb
<h1>Editing Image</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_image %> |
<%= link_to 'Back', admin_images_path %>

app/views/admin/images/index.html.erb
<%= content_tag :div, :class => 'page-header' do %>
  <%= content_tag :h1 do %>
  Image List
  <% end %>
<% end %>

<table class="table table-striped table-bordered">
	<thead>
  <tr>
    <th>Thumbnail</th>
    <th>Image URL</th>
    <th></th>
  </tr>
  </thead>
  <tbody>
<% @admin_images.each do |admin_image| %>

  <tr>
  <td><%= image_tag admin_image.image.thumb.url %>
    <td><%= admin_image.image.url %></td>
    <td><%= link_to "<i class='icon-trash icon-white'></i>&nbsp;Delete".html_safe,
                [:admin, admin_image],
                :confirm => 'Are you sure?',
                :method => :delete, 
                :id => "destroy_#{admin_image.id}",
                :class => 'btn btn-danger delete-page',
                "data-content" => 'This will irreversibly delete all sizes of this image.', 
                "data-original-title" => 'Are You Sure?' %></td>
  </tr>
<% end %>
  </tbody>
</table>

<br />
<hr>
<%= link_to "<i class='icon-play-circle icon-white'></i>&nbsp;Add an Image".html_safe, 
            new_admin_image_path,
            :class => 'btn btn-success' %>

app/views/admin/images/new.html.erb
<div class='page-header'>
  <h1>New Image</h1>
</div>
<%= render 'form' %>
<%= link_to "Cancel", admin_images_path, :class => 'btn' %>

app/views/admin/images/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_admin_image_path(@admin_image) %> |
<%= link_to 'Back', admin_images_path %>