config/routes.rb
Northcantonchurch::Application.routes.draw do

  root :to => 'main#content_page'

  mount Ckeditor::Engine => '/ckeditor'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }, :path_names => {:sign_in => 'login', :sign_out => 'logout'}
  devise_scope :user do
    get "/logout" => "devise/sessions#destroy"
  end

  resources :files
  resources :file_browsers

  resources :user_sessions
  
  resources :pages, :menu_items

  namespace :admin do
    resources :pages
    resources :menu_items
    post "menu_items/sort" => 'menu_items#sort'
    resources :images
    match '/page-versions/show/:id' => 'page_versions#show', :as => "page_versions_show"
    match '/page-versions/restore/:id' => 'page_versions#restore', :as => "page_versions_restore"
    resources :users
    post 'users/toggle-admin' => 'users#toggle_admin'
  end

  match '/admin' => 'admin#index', :as => 'admin'

  match ':controller/:action/:id'
  match ':controller/:action/:id.:format'

  #All content pages
  match ':path' => 'main#content_page'
end

app/models/user.rb
class User < ActiveRecord::Base

  devise :omniauthable
  
  has_many :roles, :through => :roles_user
  has_many :roles_user
  
  def self.find_for_open_id(access_token, signed_in_resource=nil)
    data = access_token.info
    if user = User.where(:email => data["email"]).first
      user
    else
      User.create!(:email => data["email"], :password => Devise.friendly_token[0,20])
    end
  end
  
  def is_admin?
    roles.map(&:name).include? 'admin'
  end
  
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  before_filter :authorize_user
  # GET /admin/users
  # GET /admin/users.xml
  def index
    @users = User.all
  end

  # GET /admin/users/1
  # GET /admin/users/1.xml
  def show
    @user = current_user
  end

  # GET /admin/users/new
  # GET /admin/users/new.xml
  def new
    @user = User.new         
  end

  # GET /admin/users/1/edit
  def edit
    @user = current_user
  end

  # POST /admin/users
  # POST /admin/users.xml
  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:notice] = 'Registration successfull.'      
      redirect_to root_url
    else
      render :action => "new"
    end
  end

  # PUT /admin/users/1
  # PUT /admin/users/1.xml
  def update
    @user = current_user  
    if @user.update_attributes(params[:user])
      flash[:notice] = 'User was successfully updated.'
      redirect_to root_url
    else
      render :action => "edit"
    end
  end

  # DELETE /admin/users/1
  # DELETE /admin/users/1.xml
  def destroy
    @user = User.find(params[:id])
    @user.destroy    
    redirect_to root_url    
  end

  def toggle_admin
    user = User.find(params[:id])
    admin_role = Role.find_by_name('admin')
    if params[:value] == 'yes'
      user.roles << admin_role
    else
      user.roles = []
    end
    render :nothing => true
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google
    @user = User.find_for_open_id(request.env["omniauth.auth"], current_user)
    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.google_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper

  def active_state_for(user)
    user.is_admin? ? 'active' : ''
  end
end

app/views/admin/users/_form.html.erb
<% form_for([:admin, @user]) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </p>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p>
    <%= f.submit 'Submit' %>
  </p>
<% end %>

app/views/admin/users/edit.html.erb
<h1>Editing user</h1>

<%= render :partial => 'form' %>

app/views/admin/users/index.html.erb
<h1>Listing users</h1>
<hr>
<table class='table table-striped table-bordered'>
<thead>
  <tr>
    <th>Username</th>
    <th>Administrator</th>
  </tr>
</thead>
<tbody>
<% @users.each do |user| %>
  <tr>
    <td><%=h user.email %></td>
    <td>
      <div class='btn-group user-control' data-toggle='buttons-radio' id='<%= dom_id(user) %>'>
        <button data-value='yes' data-user-id='<%= user.id %>' class='btn btn-success <%= user.is_admin? ? 'active' : '' %>'>Yes</a></button>
        <button data-value='no' data-user-id='<%= user.id %>' class='btn btn-danger <%= user.is_admin? ? '' : 'active' %>'>No</button>
      </div>
    </td>
  </tr>

<% end %>
</tbody>
</table>

app/views/admin/users/new.html.erb
<h1>New user</h1>

<%= render :partial => 'form' %>

<%= link_to 'Back', admin_users_path %>

app/views/admin/users/show.html.erb
<p>
  <b>Username:</b>
  <%=h @user.username %>
</p>

<p>
  <b>Email address:</b>
  <%=h @user.email_address %>
</p>

<p>
  <b>Password:</b>
  <%=h @user.password %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>