config/routes.rb
Northcantonchurch::Application.routes.draw do

  root :to => 'main#content_page'

  mount Ckeditor::Engine => '/ckeditor'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }, :path_names => {:sign_in => 'login', :sign_out => 'logout'}
  devise_scope :user do
    get "/logout" => "devise/sessions#destroy"
  end

  resources :files
  resources :file_browsers

  resources :user_sessions
  
  resources :pages, :menu_items

  namespace :admin do
    resources :pages
    resources :menu_items
    post "menu_items/sort" => 'menu_items#sort'
    resources :images
    match '/page-versions/show/:id' => 'page_versions#show', :as => "page_versions_show"
    match '/page-versions/restore/:id' => 'page_versions#restore', :as => "page_versions_restore"
    resources :users
    post 'users/toggle-admin' => 'users#toggle_admin'
  end

  match '/admin' => 'admin#index', :as => 'admin'

  match ':controller/:action/:id'
  match ':controller/:action/:id.:format'

  #All content pages
  match ':path' => 'main#content_page'
end

app/models/page_version.rb
class PageVersion < ActiveRecord::Base
  belongs_to :page
end

app/controllers/admin/page_versions_controller.rb
class Admin::PageVersionsController < AdminController
  before_filter :authorize_user
  
  def show
    @page_version = PageVersion.find(params[:id])
  end

  def restore
    @page_version = PageVersion.find(params[:id])
    page = @page_version.page
    if page.revert_to!(@page_version.version)
      flash[:notice] = "Page successfuly restored to version #{@page_version.version}."
      redirect_to admin_pages_path
    else      
      flash[:error] = "Page could not be restored."
      redirect_to admin_page_version_path(@page_version)
    end
  end

end

app/helpers/admin/page_version_helper.rb
module Admin::PageVersionHelper
end

app/views/admin/page_versions/show.html.erb
<h2>Page Version: <%= @page_version.version %></h2>
<strong>Title:</strong> <%= @page_version.title %><br />
<strong>Keywords:</strong> <%= @page_version.keywords %><br />
<strong>Description:</strong> <%= @page_version.description %><br />
<strong>URL:</strong> <%= @page_version.url_tag %><br />
<strong>Content:</strong><br /><%= raw(@page_version.content) %>

<%= link_to "Make this live", admin_page_versions_restore_url(@page_version) %>